##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  UTILITY: ${LB_UTILITY}

stages:
  Utility:
    actions:
    
      - type: shell
        command: echo 'Running ${UTILITY}'    

      - type: liquibase
        if: "${UTILITY} == connect"
        command: connect

      - type: liquibase
        if: "${UTILITY} == history"
        command: history

      - type: liquibase
        if: "${UTILITY} == status"
        command: status