##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  UTILITY: targeting_list2
  CHECKNAME: RollbackRequired
  TARGETING_TYPE: ignore
  FILTER: teams
  FILTER_VALUE: test
  TARGETING_ID: test
  TARGETING_REASON: test
  TARGETING_EXPIRATION: 2h
  AWS_S3_BUCKET: asmith-s3-extension-demo
  TARGETING_FILE: s3://asmith-s3-extension-demo/checks-targeting/liquibase.checks-settings.targeting.yaml
  CHECKS_SETTINGS_FILE: s3://asmith-s3-extension-demo/checks-targeting/liquibase.checks-settings.conf

stages:

  Checks Targeting:
    actions:    

      - type: shell
        if: "${UTILITY} == targeting_add"
        command: |
          #!/usr/bin/env bash
          set -e

          ARGS=(--checkname="${CHECKNAME}" --type="${TARGETING_TYPE}" --targeting-file="${TARGETING_FILE}" --checks-settings-file="${CHECKS_SETTINGS_FILE}")

          if [[ -n "${FILTER}" && -n "${FILTER_VALUE}" && "${FILTER_VALUE}" != "''" && "${FILTER}" != "''" ]]; then
            ARGS+=("--${FILTER}-filter=${FILTER_VALUE}")
          fi

          if [[ -n "${TARGETING_ID}" ]]; then
            ARGS+=(--id="${TARGETING_ID}")
          fi

          if [[ -n "${TARGETING_REASON}" ]]; then
            ARGS+=(--reason="${TARGETING_REASON}")
          fi

          if [[ -n "${TARGETING_EXPIRATION}" ]]; then
            ARGS+=(--expiration="${TARGETING_EXPIRATION}")
          fi

          echo "Running: liquibase checks targeting add ${ARGS[@]}"
          liquibase checks targeting add "${ARGS[@]}"

      - type: shell
        if: "${UTILITY} == targeting_remove"
        command: |
          #!/usr/bin/env bash
          set -e

          ARGS=(--id="${TARGETING_ID}" --targeting-file="${TARGETING_FILE}" --checks-settings-file="${CHECKS_SETTINGS_FILE}")

          echo "Running: liquibase checks targeting remove ${ARGS[@]}"
          liquibase checks targeting remove "${ARGS[@]}"

      - type: shell
        if: "${UTILITY} == targeting_list"
        command: |
          #!/usr/bin/env bash
          set -e

          ARGS=(--targeting-file="${TARGETING_FILE}" --checks-settings-file="${CHECKS_SETTINGS_FILE}")

          echo "Running: liquibase checks targeting list ${ARGS[@]}"
          liquibase checks targeting list "${ARGS[@]}"

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: checks targeting list
      cmdArgs: { targeting-file: "${TARGETING_FILE}", checks-settings-file: "${CHECKS_SETTINGS_FILE}"}
          