##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  UTILITY: ${LB_UTILITY}
  CHECKNAME: ${LB_CHECKNAME}
  TARGETING_TYPE: ${LB_TARGETING_TYPE}
  FILTER: ${LB_FILTER}
  FILTER_VALUE: ${LB_FILTER_VALUE}

stages:
  Utility:
    actions:
    
      - type: shell
        command: echo 'Running ${UTILITY}'    

      - type: liquibase
        if: "${UTILITY} == targeting_add"
        command: checks targeting add
        cmdArgs: {  checkname: "${CHECKNAME}", type: "${TARGETING_TYPE}", targeting-file: "checks/liquibase.checks-settings.targeting.yaml", "${FILTER}-filter": "${FILTER_VALUE}" }
